config/routes.rb
Erp::Application.routes.draw do
  resources :users, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :partners, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :products, :only => [:index, :edit, :show, :update, :new, :create, :destroy] 
  resources :search, :only => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :productpartner, :only => [:create, :destroy]

  resources :partners do
    member do
      get :products
    end
  end  

  root :to => "pages#home"

  match '/contact' => "pages#contact"
  match '/help' => "pages#help"
  match '/about' => "pages#about"
  match '/signup',  :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/partner.rb
# == Schema Information
# Schema version: 20121017210129
#
# Table name: products
#
#  id                 :integer         not null, primary key
#  company            :string(255)
#  name               :string(255)
#  address            :string(255)
#  city               :string(255)
#  postal_code        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  email			        :string(255)
#  active             :boolean

class Partner < ActiveRecord::Base
  attr_accessible :active, :address, :city, :company, :created_at, :email, :name, :postal_code, :updated_at
  validates_presence_of :address, :city, :company, :name, :email, :postal_code
  
  # has_many :productpartner
  has_many :product, :through => :productpartner, :dependent => :destroy, :source => :partner_id
  # has_and_belongs_to_many :product

  def self.search(search)
  	if search
    	find(:all, :conditions => ['company LIKE ?', "%#{search}%"])
  	else
    	find(:all)
  	end
  end

  def addproduct!(partnered)
    partner.productpartner.create!(:partner_id => partner.id)
  end
  
  def deleteproduct!(partnered)
    partner.productpartner.find_by_partnered_id(partnered).destroy
  end  

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
    before_filter :only => [:index, :edit, :show, :update, :new, :create, :destroy]

    def index
        @partners = Partner.paginate(:page => params[:page])
        @partnersearch = Partner.search(params[:search])
    end 

    def edit
        @partner = Partner.find(params[:id])
    end

    def show
        @partner = Partner.find(params[:id])
        @productsearch = Product.search(params[:search])
        @productsearchadd = Product.search(params[:search])
    end

    def update
        @partner = Partner.find(params[:id])
        if @partner.update_attributes(params[:partner])
            redirect_to root_path
        else
            render "edit"
        end
    end

    def new
        @partner  = Partner.new
        @title = "Add partner"
    end

    def create
        @partner = Partner.new(params[:partner])
        if @partner.save
            redirect_to root_path, :flash => { :success => "Add partner is ok!" }
        else
            @title = "Add partner"
            render 'new'
        end
    end

    def destroy
        @partner = Partner.find(params[:id])
        @partner.destroy
        redirect_to root_path, :flash => { :success => "partner deleted!" }
    end		
end

app/helpers/partner_helper.rb
module PartnerHelper
end

app/views/partners/_fields.html.erb
<div class="field">
  <%= f.label :company %>
  <%= f.text_field :company %>
</div>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div>
<div class="field">
  <%= f.label :city %>
  <%= f.text_field :city %>
</div>
<div class="field">
  <%= f.label :postal_code %>
  <%= f.text_field :postal_code %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :active %>
  <%= f.radio_button :active, "0" %>
</div>

app/views/partners/_partner.html.erb
<section>    
    <h3><%= partner.company %></h3>
    <span class="description"><%= partner.email %></span>
    <nav>
      <ul>
      <li><%= link_to 'Show', partner %></li>
      <li><%= link_to 'Edit', edit_partner_path(partner), :method => :edit %></li>
      <li><%= link_to 'Delete', partner, :method => :delete,
                                         :confirm => 'You sure?',
                                         :title => partner.name,
                                         :class => 'btn btn-primary' %></li>
      </ul>
    </nav>  
</section>

app/views/partners/edit.html.erb
<%= render 'pages/menu' %>

<div class="span9">

<h2>Edit partner <%= @partner.company %></h2>

<%= form_for(@partner) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update partner", :class => "btn btn-primary" %>
  </div>

<% end %>


</div><!--/span-->
</div><!--/row-fluid-->

app/views/partners/index.html.erb
<%= render 'pages/menu' %>

<div class="span9">
<h2>List partners</h2>
<nav>
<ul>
    <li>
	<%= link_to 'New', new_partner_path, :class => 'btn btn-primary' %></li>
</ul>
</nav>

<% if @partners.empty? %>

  <section>
      <em>No partners found</em>
  </section>    

<% else %>

  <div class="giant-btn">
      <%= form_tag partners_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search], :class => 'input-giant' %>
          <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
        </p>
      <% end %>
  </div>

  <% if params[:search].present? %>

  	<%= render @partnersearch %> 

  <% else %>

  	<%= will_paginate %>

  	  <%= render @partners %>

  	<%= will_paginate %>

  <% end %>

<% end %>


</div><!--/span-->
</div><!--/row-fluid-->

app/views/partners/new.html.erb
<%= render 'pages/menu' %>

<div class="span9">
	<h2>New partner</h2>

	<%= form_for(@partner) do |f| %>
	  <%= render 'fields', :f => f %>
	  <div class="actions">
	    <%= f.submit "Add partner", :class => "btn btn-primary" %>
	  </div>
	<% end %>
</div>

</div><!--/span-->
</div><!--/row-fluid-->

app/views/partners/show.html.erb
<%= render 'pages/menu' %>

<div class="span9">

    <h2><%= @partner.company %></h2>  
    <nav>
      <ul>
      <li><%= link_to 'back', partners_path %></li>
      <li><%= link_to 'Edit', edit_partner_path(@partner), :method => :edit %></li>
      <li><%= link_to 'Delete', @partner, :method => :delete,
                                         :confirm => 'You sure?',
                                         :title => @partner.company,
                                         :class => 'btn btn-primary' %></li>
      </ul>
    </nav>    

    <span class="email"><%= @partner.email %></span>
    <div class="adr">
      <div class="street-address"><%= @partner.address %></div>
      <div class="postal-code"><%= @partner.postal_code %></div>
      <div class="locality"><%= @partner.city %></div>
    </div>

    <hr/>    
    <h2>Products for this partner</h2> 

    <hr/>    

    <nav>
      <ul>
      <li><%= link_to 'Search product', "#", :remote => true, :class => "btn btn-primary add-product" %></li>
      </ul>
    </nav>

    <div class="alert alert-info add-product-partner">
    <button type="button" class="close" data-dismiss="alert">×</button>

    <h2>Add Products for this partner</h2>
    <div class="giant-btn">
        <%= form_tag "", :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search], :class => 'input-giant' %>
            <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
          </p>
        <% end %>
    </div>    
    </div>

    <% if params[:search].present? %>

      <%= render 'products/productsearchadd' %> 

    <% end %>

</div><!--/span-->
</div><!--/row-fluid-->

app/views/partners/update.html.erb
<%= render 'pages/menu' %>

<div class="span9">

<h2>Update partner <%= @partner.company %></h2>

<%= form_for(@partner) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Add partner", :class => "btn btn-primary" %>
  </div>
<% end %>

</div><!--/span-->
</div><!--/row-fluid-->