config/routes.rb
Erp::Application.routes.draw do
  resources :users, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :partners, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :products, :only => [:index, :edit, :show, :update, :new, :create, :destroy] 
  resources :search, :only => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :productpartner, :only => [:create, :destroy]

  resources :partners do
    member do
      get :products
    end
  end  

  root :to => "pages#home"

  match '/contact' => "pages#contact"
  match '/help' => "pages#help"
  match '/about' => "pages#about"
  match '/signup',  :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/pages/_menu.html.erb
     
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Quick Access</li>
              <li><%= link_to "List partners", '/partners' %></li>
              <li><%= link_to "List products", '/products' %></li>
              <li><%= link_to "List users", '/users' %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>

	<%= render 'pages/menu' %>

        <div class="span9">
          <div class="hero-unit">
            <h1>Hello, dude!</h1>
            <p>This is a small application with Ruby on Rails realize and Bootstrap, it is coded with my little hand as a demonstration.This is an example of what you can do with HTML5, CSS, some Javascript bootstrap and RoR.</p>

			<p>Enjoy!</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
          </div>
          <div class="row-fluid">
			<div class="span4">
				<h2>Lastest partners</h2>
				<% if @partners.empty? %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_partner_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>				
      				<em>No partners found</em>  
				<% else %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_partner_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>					
					<%= render @partners %>
				<% end %>
			</div>
			<div class="span4">
				<h2>Lastest products</h2>
				<% if @products.empty? %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_product_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>				
      				<em>No products found</em>  
				<% else %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_product_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>						
					<%= render @products %>
				<% end %>				
			</div>
			<div class="span4">
				<h2>Lastest users</h2>
				<% if @users.empty? %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>					
      				<em>No users found</em>  
				<% else %>
					<nav>
					<ul>
					    <li>
						<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %></li>
					</ul>
					</nav>				
					<%= render @users %>
				<% end %>					
			</div>
          </div><!--/row-->

        </div><!--/span-->
        </div><!--/row-fluid-->


<% else %>

<div class="row-fluid">
<div class="span12">

	<div class="hero-unit">
	<h1>Dude!</h1>
	<p>You love your business, learns to love the frameworks and makes life easy for those around you.</p>
	</div>

	<div class="giant-btn">
	<%= link_to "Sign up now!", signup_path, :class => "btn btn-primary" %>
	</div>		

</div><!--/span-->
</div>

<% end %>