config/routes.rb
Erp::Application.routes.draw do
  resources :users, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :partners, :only => [:index, :edit, :show, :update, :new, :create, :destroy]
  resources :products, :only => [:index, :edit, :show, :update, :new, :create, :destroy] 
  resources :search, :only => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :productpartner, :only => [:create, :destroy]

  resources :partners do
    member do
      get :products
    end
  end  

  root :to => "pages#home"

  match '/contact' => "pages#contact"
  match '/help' => "pages#help"
  match '/about' => "pages#about"
  match '/signup',  :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<hr />
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", 'http://news.railstutorial.org/' %></li>
      <li><%= link_to "Rails Tutorial", 'http://railstutorial.org/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul class="nav">
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
  
  <h1><%= link_to "Mini ERP", root_path %></h1>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'bootstrap/css/bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag :application, :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %> 
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container-fluid">
	   <%= render 'layouts/header' %>

        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>

    <%= render 'layouts/footer' %>
  </div><!--/container-fluid-->
  <%= debug(params) if Rails.env.development? %>

  <%= javascript_include_tag 'prototype' %>
  <%= javascript_include_tag 'application' %>  
</body>
</html>